# Generated by Django 5.2.15 on 2026-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Capability scopes carried by this token. Empty list = ``read`` only (least privilege). Known values: ``read``, ``write``, ``admin``. Admin-only endpoints require ``admin``.",
            ),
        ),
        # Backfill: tokens created before scopes existed kept full
        # superuser-level access via the surrounding ``user``. Pin them to
        # ``read`` so the migration cannot silently widen privilege.
        # Operators who need write or admin on pre-existing tokens revoke
        # and recreate them.
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model("accounts", "ApiToken")
                .objects.filter(scopes=[])
                .update(scopes=["read"])
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
