# Generated by Django 5.2.15 on 2026-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_emailchangerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThrottleCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(db_index=True, max_length=32)),
                ("key", models.CharField(max_length=128)),
                ("window_start", models.DateTimeField()),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "key", "window_start"],
                        name="accounts_th_scope_2393ca_idx",
                    )
                ],
                "unique_together": {("scope", "key", "window_start")},
            },
        ),
    ]
