# Generated by Django 5.2.15 on 2026-06-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_throttlecounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
