# Generated by Django 5.2.15 on 2026-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_locked_at_user_locked_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "from_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("to_emails", models.JSONField(default=list)),
                ("use_ascii_passthrough", models.BooleanField(default=False)),
                (
                    "audit_action",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "target_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("next_retry_at", models.DateTimeField(db_index=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["next_retry_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="accounts_ou_status_4da4ed_idx",
                    )
                ],
            },
        ),
    ]
