# Generated by Django 5.2.15 on 2026-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_outboundemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundemail",
            name="audit_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
