# Generated by Django 5.2.15 on 2026-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_outboundemail_audit_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("read_only", models.BooleanField(default=True)),
                ("message", models.TextField(blank=True, default="")),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_by_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
