# Generated by Django 5.2.15 on 2026-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_last_auth_alert_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_theme',
            field=models.CharField(choices=[('teal', 'Teal'), ('indigo', 'Índigo'), ('amber', 'Ámbar'), ('violet', 'Violeta')], default='teal', max_length=16),
        ),
    ]
