"""Regression coverage for Phase 3 #6 (mypy static type checking)
of the 2026-06-20 roadmap.

Pins:
* mypy config present in pyproject.toml with django-stubs plug-in.
* per-module overrides for view modules (decorator-narrowing
  invariant the type checker cannot see) and untyped 3rd-party
  libs.
* mypy + django-stubs in requirements-dev.
* CI workflow runs ``python -m mypy src/``.
* Pre-commit hook configured to run mypy on src/.

Does NOT actually invoke mypy — that runs in CI and locally on
pre-commit. Running it here would couple unit tests to mypy's
import time (~5s per invocation).
"""
from __future__ import annotations

import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _read(path: str) -> str:
    return (ROOT / path).read_text()


def _pyproject() -> dict:
    return tomllib.loads(_read("pyproject.toml"))


# ---------------------------------------------------------------------------
# mypy config
# ---------------------------------------------------------------------------

def test_mypy_config_present():
    py = _pyproject()
    mypy_cfg = py.get("tool", {}).get("mypy", {})
    assert mypy_cfg, "[tool.mypy] section missing from pyproject.toml"
    assert mypy_cfg.get("mypy_path") == "src", \
        "mypy_path should point at src/ so the type checker finds first-party modules"
    assert "mypy_django_plugin.main" in (mypy_cfg.get("plugins") or []), \
        "django-stubs plugin must be configured so ORM types narrow correctly"


def test_django_stubs_module_pointer_set():
    py = _pyproject()
    stubs_cfg = py.get("tool", {}).get("django-stubs", {})
    assert stubs_cfg.get("django_settings_module") == "ameli_web.settings", \
        "[tool.django-stubs].django_settings_module must point at the canonical settings"


def test_mypy_view_modules_have_decorator_narrowing_override():
    """View modules sit behind @login_required / @superadmin_required;
    request.user is a real User at runtime but the type checker
    only sees ``User | AnonymousUser``. The override disables the
    union-attr / call-arg codes on those modules with a comment
    pointing at the runtime invariant.
    """
    py = _pyproject()
    overrides = py.get("tool", {}).get("mypy", {}).get("overrides", [])
    view_override = next(
        (o for o in overrides
         if "ameli_web.accounts.views" in (o.get("module") or [])
         and "ameli_web.admin_views" in (o.get("module") or [])),
        None,
    )
    assert view_override is not None, \
        "expected an override block covering both view modules"
    disabled = view_override.get("disable_error_code") or []
    assert "union-attr" in disabled
    assert "call-arg" in disabled


def test_mypy_ignores_tests_and_migrations():
    py = _pyproject()
    excluded = py.get("tool", {}).get("mypy", {}).get("exclude") or []
    # Migrations are autogenerated; tests have their own typing rhythm.
    assert any("tests/" in e for e in excluded)
    assert any("migrations" in e for e in excluded)


# ---------------------------------------------------------------------------
# Dev deps + CI + pre-commit wiring
# ---------------------------------------------------------------------------

def test_mypy_in_dev_deps():
    dev = _read("requirements-dev.txt")
    assert "mypy>" in dev or "mypy==" in dev, \
        "mypy must be in requirements-dev.txt"
    assert "django-stubs>" in dev or "django-stubs==" in dev, \
        "django-stubs must be in requirements-dev.txt for ORM type narrowing"


def test_ci_workflow_runs_mypy():
    ci = _read(".github/workflows/ci.yml")
    assert "python -m mypy" in ci, \
        "CI must invoke mypy explicitly so type regressions fail the build"
    assert "Mypy" in ci or "mypy" in ci, \
        "CI step name should mention mypy"


def test_pre_commit_config_includes_mypy_hook():
    pre = _read(".pre-commit-config.yaml")
    assert "mirrors-mypy" in pre, \
        "pre-commit should run mypy on commit so type regressions are caught locally"
    assert "django-stubs" in pre, \
        "the mypy hook needs django-stubs as an additional_dependency"
