"""Regression coverage for Phase 1 (DX foundation) of the
2026-06-20 improvements roadmap.

Pins the static contract of pre-commit + coverage configuration
so a refactor that drops the floor / removes a hook fails fast.

Items covered:
* #1 pre-commit: .pre-commit-config.yaml exists, lists ruff +
  detect-secrets + hygiene hooks; .secrets.baseline exists.
* #2 coverage: pyproject.toml has [tool.coverage.*] sections;
  fail_under is at the agreed threshold; CI workflow invokes
  ``coverage run`` and ``coverage report``.
"""
from __future__ import annotations

import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _read(path: str) -> str:
    return (ROOT / path).read_text()


# ---------------------------------------------------------------------------
# #1 — pre-commit configuration
# ---------------------------------------------------------------------------

def test_pre_commit_config_exists():
    assert (ROOT / ".pre-commit-config.yaml").is_file()


def test_pre_commit_config_lists_ruff_hooks():
    body = _read(".pre-commit-config.yaml")
    assert "astral-sh/ruff-pre-commit" in body
    assert "id: ruff" in body
    assert "id: ruff-format" in body


def test_pre_commit_config_lists_detect_secrets():
    body = _read(".pre-commit-config.yaml")
    assert "Yelp/detect-secrets" in body
    assert "id: detect-secrets" in body
    # The baseline argument must be present; running without it
    # would re-flag every documented fixture on every commit.
    assert "--baseline" in body
    assert ".secrets.baseline" in body


def test_pre_commit_config_lists_hygiene_hooks():
    body = _read(".pre-commit-config.yaml")
    # The hygiene bundle catches papercuts the linters miss.
    for hook_id in (
        "trailing-whitespace",
        "end-of-file-fixer",
        "check-yaml",
        "check-toml",
        "check-merge-conflict",
        "check-added-large-files",
    ):
        assert f"id: {hook_id}" in body, f"hygiene hook missing: {hook_id}"


def test_secrets_baseline_exists():
    """detect-secrets ships with an explicit baseline so the hook
    only flags NEW secrets, not the documented fixtures already in
    the tree (Fernet key examples in docs, etc.).
    """
    baseline = ROOT / ".secrets.baseline"
    assert baseline.is_file()
    # Cheap sanity: the baseline is valid JSON with a results key.
    import json
    data = json.loads(baseline.read_text())
    assert "results" in data, "baseline must carry a results key"


def test_pre_commit_in_dev_deps():
    dev = _read("requirements-dev.txt")
    assert "pre-commit>" in dev or "pre-commit==" in dev, \
        "pre-commit must be in requirements-dev.txt so contributors can install it"
    assert "detect-secrets>" in dev or "detect-secrets==" in dev, \
        "detect-secrets must be in requirements-dev.txt"


# ---------------------------------------------------------------------------
# #2 — coverage configuration
# ---------------------------------------------------------------------------

def _pyproject() -> dict:
    return tomllib.loads(_read("pyproject.toml"))


def test_coverage_run_section_present():
    py = _pyproject()
    cov_run = py.get("tool", {}).get("coverage", {}).get("run", {})
    assert cov_run.get("source") == ["src"], \
        "coverage source must be the src/ tree only"
    assert cov_run.get("branch") is True, \
        "branch coverage must be on (catches if/else missed paths)"


def test_coverage_report_threshold_at_85():
    py = _pyproject()
    cov_rep = py.get("tool", {}).get("coverage", {}).get("report", {})
    assert cov_rep.get("fail_under") == 85, (
        f"coverage fail_under should be 85 (Phase 1 floor); "
        f"got {cov_rep.get('fail_under')!r}. Raise the floor with new "
        f"coverage; never lower it without an explicit ratification."
    )


def test_coverage_report_excludes_migrations_and_boot_files():
    py = _pyproject()
    omit = py.get("tool", {}).get("coverage", {}).get("run", {}).get("omit", [])
    # migrations are autogenerated; wsgi/asgi are boot files exercised
    # by django at runtime but never by pytest -> excluding them
    # avoids artificially depressing the percentage.
    assert any("migrations" in p for p in omit), "migrations should be omitted"
    assert any("wsgi" in p for p in omit), "wsgi.py should be omitted"


def test_coverage_in_dev_deps():
    dev = _read("requirements-dev.txt")
    assert "coverage>" in dev or "coverage==" in dev, \
        "coverage must be in requirements-dev.txt"


def test_ci_workflow_runs_coverage():
    ci = _read(".github/workflows/ci.yml")
    assert "coverage run" in ci, \
        "CI must wrap pytest with `coverage run` to measure coverage"
    assert "coverage report" in ci, \
        "CI must invoke `coverage report` so the fail_under threshold trips the build"
