# Generated by Django 5.2.15 on 2026-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="hmac",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="prev_hmac",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
