"""Compute SRI hashes for the Swagger UI + ReDoc bundles loaded by
``dashboard/views.py``.

Usage:

    python tools/sri_compute.py

Defaults to the versions pinned in ``dashboard/views.py``
(``SWAGGER_UI_VERSION`` / ``REDOC_VERSION``). Output is the four env
var lines you paste into ``/etc/.../app.env``:

    AMELI_APP_SRI_SWAGGER_UI_CSS=sha384-...
    AMELI_APP_SRI_SWAGGER_UI_BUNDLE=sha384-...
    AMELI_APP_SRI_SWAGGER_UI_PRESET=sha384-...
    AMELI_APP_SRI_REDOC_BUNDLE=sha384-...

Re-run this whenever you bump ``SWAGGER_UI_VERSION`` or
``REDOC_VERSION``. The script makes HTTP requests to
``cdn.jsdelivr.net``; run it from a host that can reach the public
internet, then transport the output to the air-gapped deploy via
your secret-management process.

Stdlib-only on purpose: this script is run from operator workstations
that may not have ``cryptography`` installed; relying on ``hashlib``
+ ``urllib`` keeps the dependency footprint zero.
"""
from __future__ import annotations

import base64
import hashlib
import sys
import urllib.error
import urllib.request
from pathlib import Path

# Default versions are read from dashboard/views.py so a version bump
# in the runtime automatically flows through here. Falls back to the
# hardcoded values below if the import fails (e.g. running this script
# from a checkout that has lost the views.py module path).
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))
try:
    from ameli_web.dashboard.views import (
        REDOC_VERSION,
        SWAGGER_UI_VERSION,
    )
except Exception:  # noqa: BLE001
    SWAGGER_UI_VERSION = "5.20.0"
    REDOC_VERSION = "2.1.5"


_BUNDLES = [
    ("AMELI_APP_SRI_SWAGGER_UI_CSS",
     f"https://cdn.jsdelivr.net/npm/swagger-ui-dist@{SWAGGER_UI_VERSION}/swagger-ui.css"),
    ("AMELI_APP_SRI_SWAGGER_UI_BUNDLE",
     f"https://cdn.jsdelivr.net/npm/swagger-ui-dist@{SWAGGER_UI_VERSION}/swagger-ui-bundle.js"),
    ("AMELI_APP_SRI_SWAGGER_UI_PRESET",
     f"https://cdn.jsdelivr.net/npm/swagger-ui-dist@{SWAGGER_UI_VERSION}/swagger-ui-standalone-preset.js"),
    ("AMELI_APP_SRI_REDOC_BUNDLE",
     f"https://cdn.jsdelivr.net/npm/redoc@{REDOC_VERSION}/bundles/redoc.standalone.js"),
]


def compute_sri(url: str) -> str:
    """Fetch ``url`` and return its ``sha384-<base64>`` SRI digest.

    Browsers reject the integrity attribute unless the algorithm
    prefix is present, so we always emit the full token (no bare
    base64 strings) — the operator can paste the output directly
    into the env var without a second step.
    """
    with urllib.request.urlopen(url, timeout=30) as resp:  # noqa: S310 — operator-controlled URL
        body = resp.read()
    digest = hashlib.sha384(body).digest()
    return f"sha384-{base64.b64encode(digest).decode('ascii')}"


def main(argv: list[str]) -> int:
    print("# Generated by tools/sri_compute.py", file=sys.stderr)
    print(f"# swagger-ui-dist@{SWAGGER_UI_VERSION}", file=sys.stderr)
    print(f"# redoc@{REDOC_VERSION}", file=sys.stderr)
    print("# Copy the lines below into your env file:", file=sys.stderr)
    print("", file=sys.stderr)
    failed = False
    for env_var, url in _BUNDLES:
        try:
            sri = compute_sri(url)
        except urllib.error.URLError as exc:
            print(f"# ERROR fetching {url}: {exc}", file=sys.stderr)
            failed = True
            continue
        print(f"{env_var}={sri}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
